name: Release
run-name: Building release package
on: 
  push:
    branches:
      - main

jobs:
  fetch-version:
    name: Fetch Next Version
    uses: dcgoodnow/sdfui/.github/workflows/tag-version.yml@main
    with:
      dryrun: true
  publish-npm:
    name: Publish package to NPM
    needs: fetch-version
    uses: dcgoodnow/sdfui/.github/workflows/upload-package.yml@main
    secrets: inherit
    with:
      version: ${{ needs.fetch-version.outputs.tagversion }}
  tag-commit:
    name: Tag new commit
    needs: publish-npm
    uses: dcgoodnow/sdfui/.github/workflows/tag-version.yml@main
    secrets: inherit
    permissions: 
      contents: write